# Generated by Django 4.2.3 on 2023-11-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('transaction_amount', models.FloatField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.transaction')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
